name: Try failure
on:
  push:
    branches:
      - "feature/composite-action-failure"
jobs:
  try-failure:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Success
        if: success()
        shell: bash
        run: |
          echo "Success"
      - name: Failure
        if: failure()
        shell: bash
        run: |
          echo "Failure"
    