name: If expression
on:
  push:
    branches: [ "feature/if-expression" ]
jobs:
  if-pull-requestis-opend:
    name: If
    runs-on: ubuntu-latest
    steps:
      - name: echo if pull request is opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: echo "pull request is opened"
