name: Node.js Matrix Build
on:
  push:
    branches: [ "feature/matrix-build" ]
jobs:
  matrix-build:
    name: Node.js ${{ matrix.os }} ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-2022]
        node: [14, 16]
    steps:
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
